<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>NexaUI.Tests</RootNamespace>
    <AssemblyName>NexaUI.Tests</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NexaUI.Core\NexaUI.Core.csproj" />
    <ProjectReference Include="..\..\src\NexaUI.Themes\NexaUI.Themes.csproj" />
    <ProjectReference Include="..\..\src\NexaUI.Icons\NexaUI.Icons.csproj" />
    <ProjectReference Include="..\..\src\NexaUI.Controls\NexaUI.Controls.csproj" />
  </ItemGroup>

</Project>