<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>NexaUI.Themes</RootNamespace>
    <AssemblyName>NexaUI.Themes</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NexaUI.Core\NexaUI.Core.csproj" />
  </ItemGroup>

</Project>